### ISSUE TITLE
issue when using yarn v2 pnp mode compiling with typescript - `fastify-swagger` can't access `fastify` package

### ISSUE THREAD

**Issue by hendrysadrak** [fastify/fastify-swagger#220]
Info about pnp: https://next.yarnpkg.com/features/pnp

## 🐛 Bug Report

```
yarn run build stdout:
.yarn/cache/fastify-swagger-npm-2.5.0-ec8013378d-2.zip/node_modules/fastify-swagger/index.d.ts(2,26): error TS2307: Cannot find module 'fastify'.
```

## To Reproduce

```json5
// package.json
{
  "dependencies": { 
    "fastify": "^2.11.0",
    "fastify-swagger": "^2.5.0"
  }
}
```

```typescript
// index.ts
import fastify from 'fastify'
import fastifySwagger from 'fastify-swagger'
```

```bash
# build the source code
$ tsc
```
 
## Fix 

To fix this `fastify` should be peer dependency of `fastify-swagger`

Will make PR

**Comment by hendrysadrak** [comment]
The current workaround for this issue is adding this to your projects yarn config:

```yaml
# yarnrc.yml

packageExtensions:
  fastify-swagger@*:
    peerDependencies:
      fastify: '*'
```
