### ISSUE TITLE
support openapi 3 `explode`

### ISSUE THREAD

**Issue by mikicho** [fastify/fastify-swagger#525]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Support openapi `explode`, we currently support `collectionFormat` for 2.0.
https://swagger.io/docs/specification/serialization/

### Motivation

support comma-separated style arrays

### Example

Not sure About the API but something like:
```
const schema = {
schema: {
    querystring: {
      type: 'object',
      properties: {
        fields: { schema: { type: 'array', items: { type: 'string', example: 'a,b' } }, "explode": false },
      }
    },
}
```
will generate:
```
...
- in: query
          name: fields
          required: false
          schema:
            type: array
            items:
              type: string
              example: a,b
          explode: false
...
```
