### ISSUE TITLE
Update README with OpenAPI v3 instead of Swagger example

### ISSUE THREAD

**Issue by melroy89** [fastify/fastify-swagger#790]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Update Fastify Swagger example with OpenAPI v3.

~~I used Swagger in the past, but I was able to set multiple hosts (aka servers) in the Swagger documentation page.~~

~~See: https://swagger.io/docs/specification/api-host-and-base-path/~~

~~For some reason [Fastify Swagger-ui](https://github.com/fastify/fastify-swagger-ui) has a screenshot of a drop-down with  servers in the README. However, I don't see any documentation how to do this. And with the `host` key I can only set 1 base domain.~~

### Motivation

You should be able to provide multiple hosts with additional description. Allowing users / admins to easily switch between different servers or environments (eg. acceptance vs production URL).

### Example

Example in Swagger v3.x YAML syntax:

```yaml
    servers:
      - url: https://api.example.com/v1
        description: Production server (uses live data)
      - url: https://sandbox-api.example.com:8443/v1
        description: Sandbox server (uses test data)
```
